/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static creatingChar.creatingCharacter.object_character;




/**
 *
 * @author allan
 */
public class Heal extends javax.swing.JFrame {

    /**
     * Creates new form Heal
     */

//int value=object_character.zycie;

    public Heal() {
        initComponents();

      champHealBar.setValue(object_character.zycie);
                
    }
    public void updateBar(int newValue) {
   /* Life.setValue(newValue);*/
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        gladHealPanel = new javax.swing.JPanel();
        champHealBar = new javax.swing.JProgressBar();
        champHealLabel = new javax.swing.JLabel();
        champHeal = new javax.swing.JTextField();
        healerPanell = new javax.swing.JPanel();
        healerLabel = new javax.swing.JLabel();
        healerName = new javax.swing.JTextField();
        healerButton = new javax.swing.JButton();
        healerBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        back.setText("Wróć");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1130, 660, 129, 29);

        gladHealPanel.setBackground(new java.awt.Color(91, 104, 94));
        gladHealPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.gray, null));
        gladHealPanel.setForeground(new java.awt.Color(91, 109, 94));
        gladHealPanel.setPreferredSize(new java.awt.Dimension(210, 300));

        champHealBar.setStringPainted(true);

        champHealLabel.setForeground(new java.awt.Color(91, 109, 94));
        champHealLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champSize.jpg")); // NOI18N
        champHealLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champHealLabel.setDoubleBuffered(true);
        champHealLabel.setPreferredSize(new java.awt.Dimension(210, 300));

        champHeal.setEditable(false);
        champHeal.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champHeal.setForeground(new java.awt.Color(91, 109, 94));
        champHeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champHeal.setText("Gladiator");
        champHeal.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout gladHealPanelLayout = new javax.swing.GroupLayout(gladHealPanel);
        gladHealPanel.setLayout(gladHealPanelLayout);
        gladHealPanelLayout.setHorizontalGroup(
            gladHealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gladHealPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champHealLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champHeal)
            .addComponent(champHealBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gladHealPanelLayout.setVerticalGroup(
            gladHealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gladHealPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champHealLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champHeal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champHealBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(gladHealPanel);
        gladHealPanel.setBounds(770, 120, 226, 373);

        healerPanell.setBackground(new java.awt.Color(91, 104, 94));
        healerPanell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.gray, null));
        healerPanell.setForeground(new java.awt.Color(91, 109, 94));
        healerPanell.setPreferredSize(new java.awt.Dimension(210, 300));

        healerLabel.setForeground(new java.awt.Color(91, 109, 94));
        healerLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/heal.jpg")); // NOI18N
        healerLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        healerLabel.setDoubleBuffered(true);
        healerLabel.setPreferredSize(new java.awt.Dimension(210, 300));

        healerName.setEditable(false);
        healerName.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        healerName.setForeground(new java.awt.Color(91, 109, 94));
        healerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        healerName.setText("Uzdrowiciel");
        healerName.setCaretColor(new java.awt.Color(91, 109, 94));
        healerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healerNameActionPerformed(evt);
            }
        });

        healerButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        healerButton.setText("Lecz");
        healerButton.setBorder(null);
        healerButton.setPreferredSize(new java.awt.Dimension(77, 31));
        healerButton.setSize(new java.awt.Dimension(77, 31));
        healerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout healerPanellLayout = new javax.swing.GroupLayout(healerPanell);
        healerPanell.setLayout(healerPanellLayout);
        healerPanellLayout.setHorizontalGroup(
            healerPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(healerName)
            .addGroup(healerPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(healerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(healerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        healerPanellLayout.setVerticalGroup(
            healerPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healerPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(healerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(healerPanell);
        healerPanell.setBounds(284, 120, 226, 370);

        healerBackGround.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/druidHeal.jpg")); // NOI18N
        getContentPane().add(healerBackGround);
        healerBackGround.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      this.setVisible(false);
     new mainMain().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void healerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healerNameActionPerformed

    private void healerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healerButtonActionPerformed
  object_character.addHeal();
  champHealBar.setValue(object_character.zycie);
    }//GEN-LAST:event_healerButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Heal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Heal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Heal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Heal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//final Heal addToBar = new Heal();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
           // public final int AddedLife=30;
   
            public void run() {
                new Heal().setVisible(true);
                //addToBar.updateBar(20);
            }
        });
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField champHeal;
    private javax.swing.JProgressBar champHealBar;
    private javax.swing.JLabel champHealLabel;
    private javax.swing.JPanel gladHealPanel;
    private javax.swing.JLabel healerBackGround;
    private javax.swing.JButton healerButton;
    private javax.swing.JLabel healerLabel;
    private javax.swing.JTextField healerName;
    private javax.swing.JPanel healerPanell;
    // End of variables declaration//GEN-END:variables
}
