/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stats;

import static creatingChar.creatingCharacter.object_character;
import static gladiatorUpdates.statsUpdate.addStatsUpdate;
import static gladiators.Postacie.CharismaSkillsAddMinusFunction;
import static gladiators.Postacie.SkillSkillsAddMinusFunction;
import static gladiators.Postacie.StrengthSkillsAddMinusFunction;
import static gladiators.Postacie.VitalitySkillsAddMinusFunction;
import main.mainMain;


/**
 *
 * @author allan
 */
public class Skills extends javax.swing.JFrame {

    /**
     * Creates new form Skills
     */
    public Skills() {
        initComponents();
        champBar.setValue(object_character.zycie);
        
        String converterToStringStrength=String.valueOf(object_character.strength);
        StrenghtPoints.setText(converterToStringStrength);
        
        String converterToStringVitality=String.valueOf(object_character.vitality);
        VitalityPoints.setText(converterToStringVitality);
        
        String converterToStringCharisma=String.valueOf(object_character.charisma);
        CharismaPoints.setText(converterToStringCharisma);
        
        String converterToStringSkill=String.valueOf(object_character.skill);
        SkillPoints.setText(converterToStringSkill);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        champPanel = new javax.swing.JPanel();
        champLabel = new javax.swing.JLabel();
        champBar = new javax.swing.JProgressBar();
        champ = new javax.swing.JTextField();
        SkillsPanel = new javax.swing.JPanel();
        Strength = new javax.swing.JTextField();
        Charisma = new javax.swing.JTextField();
        Vitality = new javax.swing.JTextField();
        Skill = new javax.swing.JTextField();
        charSkillTotal = new javax.swing.JLabel();
        StrenghtPoints = new javax.swing.JTextField();
        CharismaPoints = new javax.swing.JTextField();
        VitalityPoints = new javax.swing.JTextField();
        SkillPoints = new javax.swing.JTextField();
        AddStrength = new javax.swing.JButton();
        MinusStrength = new javax.swing.JButton();
        AddCharisma = new javax.swing.JButton();
        MinusCharisma = new javax.swing.JButton();
        AddVitality = new javax.swing.JButton();
        MinusVitality = new javax.swing.JButton();
        AddSkill = new javax.swing.JButton();
        MinusSkill = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        champPanel.setBackground(new java.awt.Color(26, 26, 26));
        champPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.gray, null));
        champPanel.setForeground(new java.awt.Color(102, 102, 102));

        champLabel.setForeground(new java.awt.Color(91, 109, 94));
        champLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champ.jpg")); // NOI18N
        champLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champLabel.setDoubleBuffered(true);

        champBar.setStringPainted(true);

        champ.setEditable(false);
        champ.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champ.setForeground(new java.awt.Color(91, 109, 94));
        champ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champ.setText("Gladiator");
        champ.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout champPanelLayout = new javax.swing.GroupLayout(champPanel);
        champPanel.setLayout(champPanelLayout);
        champPanelLayout.setHorizontalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champ)
            .addComponent(champBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        champPanelLayout.setVerticalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(champPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, -1, 320));

        SkillsPanel.setBackground(new java.awt.Color(26, 26, 26));
        SkillsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        Strength.setEditable(false);
        Strength.setBackground(new java.awt.Color(26, 26, 26));
        Strength.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Strength.setForeground(new java.awt.Color(255, 255, 255));
        Strength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Strength.setText("Siła");
        Strength.setBorder(null);
        Strength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrengthActionPerformed(evt);
            }
        });

        Charisma.setEditable(false);
        Charisma.setBackground(new java.awt.Color(26, 26, 26));
        Charisma.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Charisma.setForeground(new java.awt.Color(255, 255, 255));
        Charisma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Charisma.setText("Charyzma");
        Charisma.setBorder(null);
        Charisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharismaActionPerformed(evt);
            }
        });

        Vitality.setEditable(false);
        Vitality.setBackground(new java.awt.Color(26, 26, 26));
        Vitality.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Vitality.setForeground(new java.awt.Color(255, 255, 255));
        Vitality.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vitality.setText("Witalność");
        Vitality.setBorder(null);

        Skill.setEditable(false);
        Skill.setBackground(new java.awt.Color(26, 26, 26));
        Skill.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Skill.setForeground(new java.awt.Color(255, 255, 255));
        Skill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Skill.setText("Zręczność");
        Skill.setBorder(null);

        charSkillTotal.setBackground(new java.awt.Color(51, 51, 51));
        charSkillTotal.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        charSkillTotal.setForeground(new java.awt.Color(255, 255, 255));
        charSkillTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        charSkillTotal.setText("Umiejętności");
        charSkillTotal.setToolTipText("");

        StrenghtPoints.setBackground(new java.awt.Color(26, 26, 26));
        StrenghtPoints.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        StrenghtPoints.setForeground(new java.awt.Color(255, 255, 255));
        StrenghtPoints.setBorder(null);
        StrenghtPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrenghtPointsActionPerformed(evt);
            }
        });

        CharismaPoints.setBackground(new java.awt.Color(26, 26, 26));
        CharismaPoints.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        CharismaPoints.setForeground(new java.awt.Color(255, 255, 255));
        CharismaPoints.setBorder(null);

        VitalityPoints.setBackground(new java.awt.Color(26, 26, 26));
        VitalityPoints.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        VitalityPoints.setForeground(new java.awt.Color(255, 255, 255));
        VitalityPoints.setBorder(null);
        VitalityPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalityPointsActionPerformed(evt);
            }
        });

        SkillPoints.setBackground(new java.awt.Color(26, 26, 26));
        SkillPoints.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        SkillPoints.setForeground(new java.awt.Color(255, 255, 255));
        SkillPoints.setBorder(null);

        AddStrength.setText("+");
        AddStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStrengthActionPerformed(evt);
            }
        });

        MinusStrength.setText("-");
        MinusStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusStrengthActionPerformed(evt);
            }
        });

        AddCharisma.setText("+");
        AddCharisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCharismaActionPerformed(evt);
            }
        });

        MinusCharisma.setText("-");
        MinusCharisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusCharismaActionPerformed(evt);
            }
        });

        AddVitality.setText("+");
        AddVitality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVitalityActionPerformed(evt);
            }
        });

        MinusVitality.setText("-");
        MinusVitality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusVitalityActionPerformed(evt);
            }
        });

        AddSkill.setText("+");
        AddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSkillActionPerformed(evt);
            }
        });

        MinusSkill.setText("-");
        MinusSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusSkillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SkillsPanelLayout = new javax.swing.GroupLayout(SkillsPanel);
        SkillsPanel.setLayout(SkillsPanelLayout);
        SkillsPanelLayout.setHorizontalGroup(
            SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkillsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Skill)
                    .addComponent(Vitality)
                    .addComponent(Charisma)
                    .addComponent(Strength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(VitalityPoints, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(CharismaPoints, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StrenghtPoints, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SkillPoints))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SkillsPanelLayout.createSequentialGroup()
                        .addComponent(AddStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SkillsPanelLayout.createSequentialGroup()
                        .addComponent(AddCharisma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusCharisma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SkillsPanelLayout.createSequentialGroup()
                        .addComponent(AddVitality, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusVitality, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SkillsPanelLayout.createSequentialGroup()
                        .addComponent(AddSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SkillsPanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(charSkillTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        SkillsPanelLayout.setVerticalGroup(
            SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkillsPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(charSkillTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Strength, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StrenghtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStrength)
                    .addComponent(MinusStrength))
                .addGap(28, 28, 28)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Charisma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CharismaPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCharisma)
                    .addComponent(MinusCharisma))
                .addGap(28, 28, 28)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddVitality)
                        .addComponent(MinusVitality))
                    .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Vitality, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VitalityPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddSkill)
                        .addComponent(MinusSkill))
                    .addGroup(SkillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Skill, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SkillPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(SkillsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 82, -1, 320));

        back.setText("Wróć");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/tlo3.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CharismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharismaActionPerformed

    private void StrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrengthActionPerformed

    private void StrenghtPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrenghtPointsActionPerformed
     
    }//GEN-LAST:event_StrenghtPointsActionPerformed

    private void VitalityPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalityPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VitalityPointsActionPerformed

    private void AddStrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStrengthActionPerformed
        //addStatsUpdate(object_character.strength,"strength");
          StrengthSkillsAddMinusFunction(1);
    }//GEN-LAST:event_AddStrengthActionPerformed

    private void MinusStrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusStrengthActionPerformed
        StrengthSkillsAddMinusFunction(0);
        addStatsUpdate(object_character.strength,"strength");    
    }//GEN-LAST:event_MinusStrengthActionPerformed

    private void MinusCharismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusCharismaActionPerformed
       CharismaSkillsAddMinusFunction(0);
       addStatsUpdate(object_character.charisma,"charisma");   
    }//GEN-LAST:event_MinusCharismaActionPerformed

    private void AddCharismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCharismaActionPerformed
       CharismaSkillsAddMinusFunction(1);
       addStatsUpdate(object_character.charisma,"charisma");   
    }//GEN-LAST:event_AddCharismaActionPerformed

    private void AddVitalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVitalityActionPerformed
       VitalitySkillsAddMinusFunction(1);
       addStatsUpdate(object_character.vitality,"vitality");   
    }//GEN-LAST:event_AddVitalityActionPerformed

    private void MinusVitalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusVitalityActionPerformed
       VitalitySkillsAddMinusFunction(0);
       addStatsUpdate(object_character.vitality,"vitality"); 
    }//GEN-LAST:event_MinusVitalityActionPerformed

    private void AddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSkillActionPerformed
       SkillSkillsAddMinusFunction(1);
       addStatsUpdate(object_character.skill,"skill"); 
    }//GEN-LAST:event_AddSkillActionPerformed

    private void MinusSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusSkillActionPerformed
       SkillSkillsAddMinusFunction(0);
       addStatsUpdate(object_character.skill,"skill"); 
    }//GEN-LAST:event_MinusSkillActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.setVisible(false);
       new mainMain().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Skills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCharisma;
    private javax.swing.JButton AddSkill;
    private javax.swing.JButton AddStrength;
    private javax.swing.JButton AddVitality;
    private javax.swing.JTextField Charisma;
    private javax.swing.JTextField CharismaPoints;
    private javax.swing.JButton MinusCharisma;
    private javax.swing.JButton MinusSkill;
    private javax.swing.JButton MinusStrength;
    private javax.swing.JButton MinusVitality;
    private javax.swing.JTextField Skill;
    private javax.swing.JTextField SkillPoints;
    private javax.swing.JPanel SkillsPanel;
    public static javax.swing.JTextField StrenghtPoints;
    private javax.swing.JTextField Strength;
    private javax.swing.JTextField Vitality;
    private javax.swing.JTextField VitalityPoints;
    private javax.swing.JButton back;
    private javax.swing.JTextField champ;
    private javax.swing.JProgressBar champBar;
    private javax.swing.JLabel champLabel;
    private javax.swing.JPanel champPanel;
    private javax.swing.JLabel charSkillTotal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
