/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lochy;

import attack_system.monsters;
import static attack_system.packNewWindowSetter.newMap;
import static attack_system.unlockLevel.unlockDungeons;
import static attack_system.unlockLevel.unlocking;
import potwor.Potwor;
import potwor.Szkielet;
import potwor.bossSpider;
import potwor.spider;
import potwor.wolf;

/**
 *
 * @author allan
 */
public class lochy extends javax.swing.JFrame {

    /** Creates new form lochy */
    public lochy() {
        initComponents();
         newMap(Wolf,boss,Spider,Skeleton);
          unlocking(0);
          /*przypisuje zycie odnawiam aby bylo wraz inicjacja mapy wznawiane*/
    }
    
  public static  Potwor Wolf = new wolf();
  public static Potwor boss = new bossSpider();
  public static Potwor Spider = new spider();
  public static Potwor Skeleton = new Szkielet();
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sceletonAttack = new javax.swing.JButton();
        spidersAttack = new javax.swing.JButton();
        Boss = new javax.swing.JButton();
        wolfsAttack = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        dungeonsBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sceletonAttack.setBackground(new java.awt.Color(59, 58, 58));
        sceletonAttack.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        sceletonAttack.setText("Szkielet");
        sceletonAttack.setBorder(null);
        sceletonAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceletonAttackActionPerformed(evt);
            }
        });
        getContentPane().add(sceletonAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, -1));

        spidersAttack.setBackground(new java.awt.Color(59, 58, 58));
        spidersAttack.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        spidersAttack.setText("Pająki");
        spidersAttack.setBorder(null);
        spidersAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spidersAttackActionPerformed(evt);
            }
        });
        getContentPane().add(spidersAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 90, -1));

        Boss.setBackground(new java.awt.Color(59, 58, 58));
        Boss.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Boss.setText("Boss");
        Boss.setBorder(null);
        Boss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BossActionPerformed(evt);
            }
        });
        getContentPane().add(Boss, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 90, -1));

        wolfsAttack.setBackground(new java.awt.Color(59, 58, 58));
        wolfsAttack.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        wolfsAttack.setText("Wilkołak");
        wolfsAttack.setBorder(null);
        wolfsAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wolfsAttackActionPerformed(evt);
            }
        });
        getContentPane().add(wolfsAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, -1));
        wolfsAttack.getAccessibleContext().setAccessibleName("wilkołak");

        Back.setBackground(new java.awt.Color(59, 58, 58));
        Back.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Back.setText("Wróć");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 90, -1));

        dungeonsBackground.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/lochy_tlo.jpg")); // NOI18N
        getContentPane().add(dungeonsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sceletonAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceletonAttackActionPerformed
       new szkieletAttack().setVisible(true);
    }//GEN-LAST:event_sceletonAttackActionPerformed

    private void wolfsAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wolfsAttackActionPerformed
       if(unlockDungeons>0  ){ new wolfAttack().setVisible(true);}
    }//GEN-LAST:event_wolfsAttackActionPerformed

    private void spidersAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spidersAttackActionPerformed
       if(unlockDungeons>1){ new spiderAttack().setVisible(true);}
    }//GEN-LAST:event_spidersAttackActionPerformed

    private void BossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BossActionPerformed
      if(unlockDungeons>2){ new bossSpiderAtack().setVisible(true);}
    }//GEN-LAST:event_BossActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
          new monsters().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lochy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lochy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lochy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lochy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lochy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Boss;
    private javax.swing.JLabel dungeonsBackground;
    private javax.swing.JButton sceletonAttack;
    private javax.swing.JButton spidersAttack;
    private javax.swing.JButton wolfsAttack;
    // End of variables declaration//GEN-END:variables

}
