/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lochy;

import static attack_system.unlockLevel.unlocking;
import static creatingChar.creatingCharacter.object_character;
import static lochy.lochy.Spider;



/**
 *
 * @author allan
 */
public class spiderAttack extends javax.swing.JFrame {

     
  int valueGlad=object_character.zycie;
  int valueSpider=Spider.potworZycie;
  
    String champInt=String.valueOf(object_character.zycie);
    String spiderInt=String.valueOf(Spider.potworZycie);
  
    public spiderAttack() {
        initComponents();
            
   champBar.setString(champInt);
   spiderBa.setString(spiderInt);
   //skeletonProgress.setMaximum(Arek.potworZycie);
   //gladiatorProgress.setMaximum(Rall.zycie);
    champBar.setValue(object_character.zycie);
    spiderBa.setValue(Spider.potworZycie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spiderPanell = new javax.swing.JPanel();
        spiderLab = new javax.swing.JLabel();
        spiderBa = new javax.swing.JProgressBar();
        spiderR = new javax.swing.JTextField();
        champPanel = new javax.swing.JPanel();
        champLabel = new javax.swing.JLabel();
        champBar = new javax.swing.JProgressBar();
        champ = new javax.swing.JTextField();
        attackBut = new javax.swing.JButton();
        backgroundSpider = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spiderPanell.setBackground(new java.awt.Color(91, 104, 94));
        spiderPanell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.gray, null));
        spiderPanell.setForeground(new java.awt.Color(91, 109, 94));

        spiderLab.setForeground(new java.awt.Color(91, 109, 94));
        spiderLab.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/spiders.jpg")); // NOI18N
        spiderLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        spiderLab.setDoubleBuffered(true);

        spiderBa.setStringPainted(true);

        spiderR.setEditable(false);
        spiderR.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        spiderR.setForeground(new java.awt.Color(91, 109, 94));
        spiderR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spiderR.setText("Gladiator");
        spiderR.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout spiderPanellLayout = new javax.swing.GroupLayout(spiderPanell);
        spiderPanell.setLayout(spiderPanellLayout);
        spiderPanellLayout.setHorizontalGroup(
            spiderPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spiderPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spiderLab, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(spiderR)
            .addComponent(spiderBa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        spiderPanellLayout.setVerticalGroup(
            spiderPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spiderPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spiderLab, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spiderR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spiderBa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(spiderPanell, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 320));

        champPanel.setBackground(new java.awt.Color(91, 104, 94));
        champPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.gray, null));
        champPanel.setForeground(new java.awt.Color(91, 109, 94));

        champLabel.setForeground(new java.awt.Color(91, 109, 94));
        champLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champ.jpg")); // NOI18N
        champLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champLabel.setDoubleBuffered(true);

        champBar.setStringPainted(true);

        champ.setEditable(false);
        champ.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champ.setForeground(new java.awt.Color(91, 109, 94));
        champ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champ.setText("Gladiator");
        champ.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout champPanelLayout = new javax.swing.GroupLayout(champPanel);
        champPanel.setLayout(champPanelLayout);
        champPanelLayout.setHorizontalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champ)
            .addComponent(champBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        champPanelLayout.setVerticalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(champPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, -1, 320));

        attackBut.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        attackBut.setText("Atakuj");
        attackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButActionPerformed(evt);
            }
        });
        getContentPane().add(attackBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        backgroundSpider.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/lochy_tlo.jpg")); // NOI18N
        getContentPane().add(backgroundSpider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButActionPerformed
             if(Spider.potworZycie==0){unlocking(3);}
        if(Spider.potworZycie > 0 && object_character.zycie > 0){
            if(Spider.potworZycie == 0 || object_character.zycie==0){
                System.out.println("MARTWI");
            }
            else{
                 object_character.atak(Spider);
                 Spider.atakPotwor(object_character);            
                 valueGlad=object_character.zycie;
                 valueSpider=Spider.potworZycie;
                 champInt=String.valueOf(object_character.zycie); 
                 spiderInt=String.valueOf(Spider.potworZycie);
     
     
                        champBar.setValue(valueGlad);
                        spiderBa.setValue(valueSpider);
                        champBar.setString(champInt);
                        spiderBa.setString(spiderInt);
                }
             if(Spider.potworZycie==0){unlocking(3);}
         if(object_character.zycie<=0){Spider.potworZycie=Spider.potworZycieWartownik;}
        }
                                            

    }//GEN-LAST:event_attackButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spiderAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spiderAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spiderAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spiderAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spiderAttack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackBut;
    private javax.swing.JLabel backgroundSpider;
    private javax.swing.JTextField champ;
    private javax.swing.JProgressBar champBar;
    private javax.swing.JLabel champLabel;
    private javax.swing.JPanel champPanel;
    private javax.swing.JProgressBar spiderBa;
    private javax.swing.JLabel spiderLab;
    private javax.swing.JPanel spiderPanell;
    private javax.swing.JTextField spiderR;
    // End of variables declaration//GEN-END:variables
}
