/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attack_system;
import static attack_system.packNewWindowSetter.newMap;
import static creatingChar.creatingCharacter.object_character;

import desert.desert;
import static desert.desert.Anubis;
import static desert.desert.bodyguardAnubis;
import static desert.desert.pers;
import static desert.desert.sphinxDesert;
import static gladiatorUpdates.experienceUpdate.expUpdateSql;
import static gladiators.Postacie.setLevelLimit;
import lochy.lochy;
import main.mainMain;
import portPiratow.port;

/**
 *
 * @author allan
 */
public class monsters extends javax.swing.JFrame {

    /**
     * Creates new form monsters
     */
    public monsters() {
        initComponents();
        expUpdateSql(object_character);
        setLevelLimit(object_character);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Catacumbs = new javax.swing.JPanel();
        catacumbsButton = new javax.swing.JButton();
        catacumbsPhoto = new javax.swing.JLabel();
        piratesPort = new javax.swing.JPanel();
        piratesPortButton = new javax.swing.JButton();
        piratesPortPhoto = new javax.swing.JLabel();
        desert = new javax.swing.JPanel();
        desertPhoto = new javax.swing.JLabel();
        desertButton = new javax.swing.JButton();
        Castle = new javax.swing.JPanel();
        castlePhoto = new javax.swing.JLabel();
        castleButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        backToMain = new javax.swing.JButton();
        chooseWay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 484));
        setPreferredSize(new java.awt.Dimension(860, 484));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Catacumbs.setBackground(new java.awt.Color(5, 27, 53));
        Catacumbs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        catacumbsButton.setBackground(new java.awt.Color(255, 255, 255));
        catacumbsButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        catacumbsButton.setText("Lochy");
        catacumbsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        catacumbsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catacumbsButtonActionPerformed(evt);
            }
        });

        catacumbsPhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/monstersLochy.jpg")); // NOI18N

        javax.swing.GroupLayout CatacumbsLayout = new javax.swing.GroupLayout(Catacumbs);
        Catacumbs.setLayout(CatacumbsLayout);
        CatacumbsLayout.setHorizontalGroup(
            CatacumbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatacumbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CatacumbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(catacumbsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(catacumbsPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CatacumbsLayout.setVerticalGroup(
            CatacumbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatacumbsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catacumbsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catacumbsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Catacumbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 136, -1, -1));

        piratesPort.setBackground(new java.awt.Color(5, 27, 53));
        piratesPort.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        piratesPortButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        piratesPortButton.setText("Port piratów");
        piratesPortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piratesPortButtonActionPerformed(evt);
            }
        });

        piratesPortPhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/MonstersPiraci.png")); // NOI18N

        javax.swing.GroupLayout piratesPortLayout = new javax.swing.GroupLayout(piratesPort);
        piratesPort.setLayout(piratesPortLayout);
        piratesPortLayout.setHorizontalGroup(
            piratesPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piratesPortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piratesPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(piratesPortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piratesPortPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        piratesPortLayout.setVerticalGroup(
            piratesPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piratesPortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(piratesPortPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piratesPortButton)
                .addContainerGap())
        );

        getContentPane().add(piratesPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 136, -1, -1));

        desert.setBackground(new java.awt.Color(5, 27, 53));
        desert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        desertPhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/Monstersdesert.jpg")); // NOI18N

        desertButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        desertButton.setText("Pustynia");
        desertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desertLayout = new javax.swing.GroupLayout(desert);
        desert.setLayout(desertLayout);
        desertLayout.setHorizontalGroup(
            desertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(desertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desertPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        desertLayout.setVerticalGroup(
            desertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desertPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desertButton)
                .addContainerGap())
        );

        getContentPane().add(desert, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 136, -1, -1));

        Castle.setBackground(new java.awt.Color(5, 27, 53));
        Castle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        castlePhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/castle.jpg")); // NOI18N

        castleButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        castleButton.setText("Zamek");

        javax.swing.GroupLayout CastleLayout = new javax.swing.GroupLayout(Castle);
        Castle.setLayout(CastleLayout);
        CastleLayout.setHorizontalGroup(
            CastleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CastleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CastleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(castleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(castlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CastleLayout.setVerticalGroup(
            CastleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CastleLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(castlePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(castleButton)
                .addContainerGap())
        );

        getContentPane().add(Castle, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 136, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Wybierz swoją drogę");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 40, 342, 48));

        backToMain.setText("Wróć");
        backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainActionPerformed(evt);
            }
        });
        getContentPane().add(backToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 90, -1));

        chooseWay.setBackground(new java.awt.Color(51, 51, 51));
        chooseWay.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/monsters.jpg")); // NOI18N
        getContentPane().add(chooseWay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 860, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void catacumbsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catacumbsButtonActionPerformed
        new lochy().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_catacumbsButtonActionPerformed

    private void piratesPortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piratesPortButtonActionPerformed
        new port().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_piratesPortButtonActionPerformed

    private void desertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desertButtonActionPerformed
new desert().setVisible(true);
this.setVisible(false);
newMap(Anubis,bodyguardAnubis,sphinxDesert,pers);
    }//GEN-LAST:event_desertButtonActionPerformed

    private void backToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainActionPerformed
        this.setVisible(false);
        new mainMain().setVisible(true);
    }//GEN-LAST:event_backToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monsters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monsters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monsters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monsters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new monsters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Castle;
    private javax.swing.JPanel Catacumbs;
    private javax.swing.JButton backToMain;
    private javax.swing.JButton castleButton;
    private javax.swing.JLabel castlePhoto;
    private javax.swing.JButton catacumbsButton;
    private javax.swing.JLabel catacumbsPhoto;
    private javax.swing.JLabel chooseWay;
    private javax.swing.JPanel desert;
    private javax.swing.JButton desertButton;
    private javax.swing.JLabel desertPhoto;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel piratesPort;
    private javax.swing.JButton piratesPortButton;
    private javax.swing.JLabel piratesPortPhoto;
    // End of variables declaration//GEN-END:variables
}
