/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creatingChar;

import static creatingChar.chooseChampSelectSQL.nickDataBase;
import static creatingChar.chooseChampSelectSQL.searchCharacters;
import static creatingChar.chooseChampSelectSQL.searchCharactersIdChampion;
import static creatingChar.creatingCharSQL.creatingPlayer;
import static creatingChar.creatingCharacter.object_character;
import static creatingChar.setNewGladiatorSQL.selectorToSetterGladiator;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static login.connect.connecting;
import main.mainMain;
/**
 *
 * @author allan
 */

public class chooseChampDes extends javax.swing.JFrame {

    /**
     * Creates new form chooseChamp
     */
    public chooseChampDes() throws SQLException {
        initComponents();
        connecting();
        creatingPlayer(nickDataBase);
       searchCharacters();//pobiera wszystkie postacie nicki i wyswietla tekst
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Characters = new javax.swing.JPanel();
        characterFourButton = new javax.swing.JButton();
        characterThreeButton = new javax.swing.JButton();
        characterOneButton = new javax.swing.JButton();
        characterOnePhoto = new javax.swing.JLabel();
        characterTwoButton = new javax.swing.JButton();
        characterOne = new javax.swing.JTextField();
        characterTwoPhoto = new javax.swing.JLabel();
        characterTwo = new javax.swing.JTextField();
        characterThreePhoto = new javax.swing.JLabel();
        characterThree = new javax.swing.JTextField();
        characterFourPhoto = new javax.swing.JLabel();
        characterFour = new javax.swing.JTextField();
        characterOneLevel = new javax.swing.JTextField();
        characterTwoLevel = new javax.swing.JTextField();
        characterThreeLevel = new javax.swing.JTextField();
        characterFourLevel = new javax.swing.JTextField();
        word = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        Characters.setBackground(new java.awt.Color(0, 0, 0));

        characterFourButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        characterFourButton.setText("Wybierz");
        characterFourButton.setPreferredSize(new java.awt.Dimension(157, 29));

        characterThreeButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        characterThreeButton.setText("Wybierz");
        characterThreeButton.setPreferredSize(new java.awt.Dimension(157, 29));
        characterThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterThreeButtonActionPerformed(evt);
            }
        });

        characterOneButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        characterOneButton.setText("Wybierz");
        characterOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterOneButtonActionPerformed(evt);
            }
        });

        characterTwoButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        characterTwoButton.setText("Wybierz");
        characterTwoButton.setPreferredSize(new java.awt.Dimension(157, 29));
        characterTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterTwoButtonActionPerformed(evt);
            }
        });

        characterOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterOneActionPerformed(evt);
            }
        });

        characterTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterTwoActionPerformed(evt);
            }
        });

        characterThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterThreeActionPerformed(evt);
            }
        });

        characterTwoLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterTwoLevelActionPerformed(evt);
            }
        });

        word.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setText("Wybierz postać");

        javax.swing.GroupLayout CharactersLayout = new javax.swing.GroupLayout(Characters);
        Characters.setLayout(CharactersLayout);
        CharactersLayout.setHorizontalGroup(
            CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharactersLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(characterOneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterOnePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CharactersLayout.createSequentialGroup()
                        .addComponent(characterOne, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterOneLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(characterTwoPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterTwoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CharactersLayout.createSequentialGroup()
                        .addComponent(characterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterTwoLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(characterThreeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(characterThreePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CharactersLayout.createSequentialGroup()
                        .addComponent(characterThree, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterThreeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(characterFourPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharactersLayout.createSequentialGroup()
                        .addComponent(characterFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterFourLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharactersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(word)
                .addGap(555, 555, 555))
        );
        CharactersLayout.setVerticalGroup(
            CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharactersLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(word)
                .addGap(45, 45, 45)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterFourLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(characterThree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterThreeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterTwoLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterOne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterOneLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterFour, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(characterTwoPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterOnePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterThreePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterFourPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(characterOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(characterThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(characterFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jTabbedPane1.addTab("Postacie", Characters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void characterThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterThreeButtonActionPerformed
        nickDataBase=characterThree.getText();
        try {
            searchCharactersIdChampion(nickDataBase);
            selectorToSetterGladiator();
        } catch (SQLException ex) {
            Logger.getLogger(chooseChampDes.class.getName()).log(Level.SEVERE, null, ex);
        }
        object_character.pobierzOpis();
       new mainMain().setVisible(true);  
       this.setVisible(false);
    }//GEN-LAST:event_characterThreeButtonActionPerformed

    private void characterTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterTwoButtonActionPerformed
         nickDataBase=characterTwo.getText();
        try {
            searchCharactersIdChampion(nickDataBase);
            selectorToSetterGladiator();
        } catch (SQLException ex) {
            Logger.getLogger(chooseChampDes.class.getName()).log(Level.SEVERE, null, ex);
        }       
        object_character.pobierzOpis();
       new mainMain().setVisible(true);  
       this.setVisible(false);
    }//GEN-LAST:event_characterTwoButtonActionPerformed

    private void characterTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterTwoActionPerformed

    private void characterThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterThreeActionPerformed

    private void characterTwoLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterTwoLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterTwoLevelActionPerformed

    private void characterOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterOneButtonActionPerformed

         nickDataBase=characterOne.getText();//pobiera nick championa
        try {
            searchCharactersIdChampion(nickDataBase);//pobiera id championa
            selectorToSetterGladiator();//pobiera wszystko wzgledem id
        } catch (SQLException ex) {
            Logger.getLogger(chooseChampDes.class.getName()).log(Level.SEVERE, null, ex);
        }
        object_character.pobierzOpis();
        
    }//GEN-LAST:event_characterOneButtonActionPerformed

    private void characterOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseChampDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseChampDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseChampDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseChampDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new chooseChampDes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(chooseChampDes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Characters;
    public static javax.swing.JTextField characterFour;
    private javax.swing.JButton characterFourButton;
    private javax.swing.JTextField characterFourLevel;
    private javax.swing.JLabel characterFourPhoto;
    public static javax.swing.JTextField characterOne;
    private javax.swing.JButton characterOneButton;
    private javax.swing.JTextField characterOneLevel;
    private javax.swing.JLabel characterOnePhoto;
    public static javax.swing.JTextField characterThree;
    private javax.swing.JButton characterThreeButton;
    private javax.swing.JTextField characterThreeLevel;
    private javax.swing.JLabel characterThreePhoto;
    public static javax.swing.JTextField characterTwo;
    private javax.swing.JButton characterTwoButton;
    private javax.swing.JTextField characterTwoLevel;
    private javax.swing.JLabel characterTwoPhoto;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables
}
