/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creatingChar;
import static creatingChar.chooseChampSelectSQL.nickDataBase;
import static creatingChar.chooseChampSelectSQL.searchCharactersIdChampion;
import static creatingChar.creatingCharSQL.creatingPlayer;
import static creatingChar.creatingCharSQL.insertPlayerEquipmentSQL;
import static creatingChar.creatingCharSQL.insertPlayerSQL;
import gladiators.Gladiator;
import gladiators.Postacie;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author allan
 */
public class creatingCharacter extends javax.swing.JFrame {
 
     public static Postacie object_character = new Gladiator();
    /**
     * Creates new form creating_character
     */
      
    public creatingCharacter() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closedMaleFemale = new javax.swing.JPanel();
        confirmPlayer = new javax.swing.JButton();
        female_panel = new javax.swing.JPanel();
        female = new javax.swing.JLabel();
        female_radio = new javax.swing.JRadioButton();
        male_panel = new javax.swing.JPanel();
        male = new javax.swing.JLabel();
        male_radio = new javax.swing.JRadioButton();
        nickPlayer = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        confirmPlayer.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        confirmPlayer.setText("Potwierdź");
        confirmPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPlayerActionPerformed(evt);
            }
        });

        female.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/female.jpg")); // NOI18N
        female.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        female_radio.setText("Kobieta");
        female_radio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout female_panelLayout = new javax.swing.GroupLayout(female_panel);
        female_panel.setLayout(female_panelLayout);
        female_panelLayout.setHorizontalGroup(
            female_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(female_radio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(female_panelLayout.createSequentialGroup()
                .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        female_panelLayout.setVerticalGroup(
            female_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(female_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(female_radio))
        );

        male.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/male.jpg")); // NOI18N
        male.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        male_radio.setText("Mężczyzna");
        male_radio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        male_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout male_panelLayout = new javax.swing.GroupLayout(male_panel);
        male_panel.setLayout(male_panelLayout);
        male_panelLayout.setHorizontalGroup(
            male_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(male_radio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        male_panelLayout.setVerticalGroup(
            male_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(male_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(male_radio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nickPlayer.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        nickPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickPlayerActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Nick");

        javax.swing.GroupLayout closedMaleFemaleLayout = new javax.swing.GroupLayout(closedMaleFemale);
        closedMaleFemale.setLayout(closedMaleFemaleLayout);
        closedMaleFemaleLayout.setHorizontalGroup(
            closedMaleFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closedMaleFemaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(closedMaleFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(closedMaleFemaleLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nickPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmPlayer))
                    .addGroup(closedMaleFemaleLayout.createSequentialGroup()
                        .addComponent(female_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(male_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closedMaleFemaleLayout.setVerticalGroup(
            closedMaleFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closedMaleFemaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(closedMaleFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(female_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(male_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(closedMaleFemaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPlayer))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(closedMaleFemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(closedMaleFemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void male_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_radioActionPerformed

    private void confirmPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPlayerActionPerformed
      
        
        nickDataBase=nickPlayer.getText();
       
         try {
             
                     
             creatingPlayer(nickDataBase);
            
             insertPlayerSQL();
             insertPlayerEquipmentSQL();
         } catch (SQLException ex) {
             Logger.getLogger(creatingCharacter.class.getName()).log(Level.SEVERE, null, ex);
         }
         
          
    
         new gameMenu().setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_confirmPlayerActionPerformed

    private void nickPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creatingCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creatingCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creatingCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creatingCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creatingCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closedMaleFemale;
    private javax.swing.JButton confirmPlayer;
    private javax.swing.JLabel female;
    private javax.swing.JPanel female_panel;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel male;
    private javax.swing.JPanel male_panel;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField nickPlayer;
    // End of variables declaration//GEN-END:variables
}
