/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portPiratow;

import static attack_system.unlockLevel.unlocking;
import static creatingChar.creatingCharacter.object_character;


import static portPiratow.port.pirate;


/**
 *
 * @author allan
 */
public class pirateAttack extends javax.swing.JFrame {

     
  int valueGlad=object_character.zycie;
  int valuePirates=pirate.potworZycie;
  
    String champInt=String.valueOf(object_character.zycie);
    String pirateInt=String.valueOf(pirate.potworZycie); //pobrana zawartosc stringa jakos pasek
  
    public pirateAttack() {
        initComponents();
            
   champBar.setString(champInt);
   pirateBa.setString(pirateInt);
    champBar.setValue(object_character.zycie);
    pirateBa.setValue(pirate.potworZycie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piratePanel = new javax.swing.JPanel();
        pirateLab = new javax.swing.JLabel();
        pirateBa = new javax.swing.JProgressBar();
        pirateR = new javax.swing.JTextField();
        champPanel = new javax.swing.JPanel();
        champLabel = new javax.swing.JLabel();
        champBar = new javax.swing.JProgressBar();
        champ = new javax.swing.JTextField();
        attackBut = new javax.swing.JButton();
        backgroundSkeleton = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piratePanel.setBackground(new java.awt.Color(64, 119, 133));
        piratePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        piratePanel.setForeground(new java.awt.Color(64, 119, 133));

        pirateLab.setForeground(new java.awt.Color(91, 109, 94));
        pirateLab.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/pirates.jpg")); // NOI18N
        pirateLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        pirateLab.setDoubleBuffered(true);

        pirateBa.setStringPainted(true);

        pirateR.setEditable(false);
        pirateR.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        pirateR.setForeground(new java.awt.Color(91, 109, 94));
        pirateR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pirateR.setText("Piraci");
        pirateR.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout piratePanelLayout = new javax.swing.GroupLayout(piratePanel);
        piratePanel.setLayout(piratePanelLayout);
        piratePanelLayout.setHorizontalGroup(
            piratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piratePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pirateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pirateR)
            .addComponent(pirateBa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        piratePanelLayout.setVerticalGroup(
            piratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piratePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pirateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pirateR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pirateBa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(piratePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 320));

        champPanel.setBackground(new java.awt.Color(64, 119, 133));
        champPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        champPanel.setForeground(new java.awt.Color(64, 119, 133));

        champLabel.setForeground(new java.awt.Color(91, 109, 94));
        champLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champ.jpg")); // NOI18N
        champLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champLabel.setDoubleBuffered(true);

        champBar.setStringPainted(true);

        champ.setEditable(false);
        champ.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champ.setForeground(new java.awt.Color(91, 109, 94));
        champ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champ.setText("Gladiator");
        champ.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout champPanelLayout = new javax.swing.GroupLayout(champPanel);
        champPanel.setLayout(champPanelLayout);
        champPanelLayout.setHorizontalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champ)
            .addComponent(champBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        champPanelLayout.setVerticalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(champPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, -1, 320));

        attackBut.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        attackBut.setText("Atakuj");
        attackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButActionPerformed(evt);
            }
        });
        getContentPane().add(attackBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        backgroundSkeleton.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/portpiratow_tlojpg.jpg")); // NOI18N
        getContentPane().add(backgroundSkeleton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButActionPerformed
             if(pirate.potworZycie > 0 && object_character.zycie > 0){
            if(pirate.potworZycie == 0 || object_character.zycie==0){
                System.out.println("MARTWI");
            }
            else{
                 object_character.atak(pirate);
                 pirate.atakPotwor(object_character);            
                 valueGlad=object_character.zycie;
                 valuePirates=pirate.potworZycie;
                 champInt=String.valueOf(object_character.zycie); 
                 pirateInt=String.valueOf(pirate.potworZycie);
     
     
                        champBar.setValue(valueGlad);
                        pirateBa.setValue(valuePirates);
                        champBar.setString(champInt);
                        pirateBa.setString(pirateInt);
                }
              if(pirate.potworZycie==0){unlocking(2);}
             if(object_character.zycie<=0){pirate.potworZycie=pirate.potworZycieWartownik;}
        }
                                            

    }//GEN-LAST:event_attackButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pirateAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pirateAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pirateAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pirateAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pirateAttack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackBut;
    private javax.swing.JLabel backgroundSkeleton;
    private javax.swing.JTextField champ;
    private javax.swing.JProgressBar champBar;
    private javax.swing.JLabel champLabel;
    private javax.swing.JPanel champPanel;
    private javax.swing.JProgressBar pirateBa;
    private javax.swing.JLabel pirateLab;
    private javax.swing.JPanel piratePanel;
    private javax.swing.JTextField pirateR;
    // End of variables declaration//GEN-END:variables
}
