/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desertCity;


import static attack_system.unlockLevel.unlocking;
import static creatingChar.creatingCharacter.object_character;
import static desert.desert.Anubis;




/**
 *
 * @author allan
 */
public class bossAnubisAttack extends javax.swing.JFrame {

      
  int valueGlad=object_character.zycie;
  int valueAnubis=Anubis.potworZycie;
  
    String champInt=String.valueOf(object_character.zycie);
    String anubisInt=String.valueOf(Anubis.potworZycie);
  
    public bossAnubisAttack() {
        initComponents();
            
   champBar.setString(champInt);
   anubisBa.setString(anubisInt);
   //skeletonProgress.setMaximum(Arek.potworZycie);
   //gladiatorProgress.setMaximum(Rall.zycie);
    champBar.setValue(object_character.zycie);
    anubisBa.setValue(Anubis.potworZycie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anubisPanel = new javax.swing.JPanel();
        anubisLab = new javax.swing.JLabel();
        anubisBa = new javax.swing.JProgressBar();
        anubisR = new javax.swing.JTextField();
        champPanel = new javax.swing.JPanel();
        champLabel = new javax.swing.JLabel();
        champBar = new javax.swing.JProgressBar();
        champ = new javax.swing.JTextField();
        attackBut = new javax.swing.JButton();
        backgroundbodyguard = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anubisPanel.setBackground(new java.awt.Color(182, 153, 111));
        anubisPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        anubisPanel.setForeground(new java.awt.Color(182, 153, 111));

        anubisLab.setForeground(new java.awt.Color(91, 109, 94));
        anubisLab.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/anubiseski.jpg")); // NOI18N
        anubisLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        anubisLab.setDoubleBuffered(true);

        anubisBa.setStringPainted(true);

        anubisR.setEditable(false);
        anubisR.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        anubisR.setForeground(new java.awt.Color(91, 109, 94));
        anubisR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anubisR.setText("Anubis");
        anubisR.setCaretColor(new java.awt.Color(91, 109, 94));
        anubisR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anubisRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anubisPanelLayout = new javax.swing.GroupLayout(anubisPanel);
        anubisPanel.setLayout(anubisPanelLayout);
        anubisPanelLayout.setHorizontalGroup(
            anubisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anubisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anubisLab, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(anubisR)
            .addComponent(anubisBa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        anubisPanelLayout.setVerticalGroup(
            anubisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anubisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anubisLab, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anubisR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(anubisBa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(anubisPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 320));

        champPanel.setBackground(new java.awt.Color(182, 153, 111));
        champPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        champPanel.setForeground(new java.awt.Color(182, 153, 111));

        champLabel.setForeground(new java.awt.Color(91, 109, 94));
        champLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champ.jpg")); // NOI18N
        champLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champLabel.setDoubleBuffered(true);

        champBar.setStringPainted(true);

        champ.setEditable(false);
        champ.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champ.setForeground(new java.awt.Color(91, 109, 94));
        champ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champ.setText("Gladiator");
        champ.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout champPanelLayout = new javax.swing.GroupLayout(champPanel);
        champPanel.setLayout(champPanelLayout);
        champPanelLayout.setHorizontalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champ)
            .addComponent(champBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        champPanelLayout.setVerticalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(champPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, -1, 320));

        attackBut.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        attackBut.setText("Atakuj");
        attackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButActionPerformed(evt);
            }
        });
        getContentPane().add(attackBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        backgroundbodyguard.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/monstersMiasto.jpg")); // NOI18N
        getContentPane().add(backgroundbodyguard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButActionPerformed
             if(Anubis.potworZycie > 0 && object_character.zycie > 0){
            if(Anubis.potworZycie == 0 || object_character.zycie==0){
                System.out.println("MARTWI");
            }
            else{
                 object_character.atak(Anubis);
                 Anubis.atakPotwor(object_character);            
                 valueGlad=object_character.zycie;
                 valueAnubis=Anubis.potworZycie;
                 champInt=String.valueOf(object_character.zycie); 
                 anubisInt=String.valueOf(Anubis.potworZycie);
     
     
                        champBar.setValue(valueGlad);
                        anubisBa.setValue(valueAnubis);
                        champBar.setString(champInt);
                        anubisBa.setString(anubisInt);
                }
            
         if(object_character.zycie<=0){ Anubis.potworZycie=Anubis.potworZycieWartownik;}
        }
                                            

    }//GEN-LAST:event_attackButActionPerformed

    private void anubisRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anubisRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anubisRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bossAnubisAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bossAnubisAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bossAnubisAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bossAnubisAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     
       
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bossAnubisAttack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar anubisBa;
    private javax.swing.JLabel anubisLab;
    private javax.swing.JPanel anubisPanel;
    private javax.swing.JTextField anubisR;
    private javax.swing.JButton attackBut;
    private javax.swing.JLabel backgroundbodyguard;
    private javax.swing.JTextField champ;
    private javax.swing.JProgressBar champBar;
    private javax.swing.JLabel champLabel;
    private javax.swing.JPanel champPanel;
    // End of variables declaration//GEN-END:variables
}
