/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desertCity;


import attack_system.monsters;
import static attack_system.packNewWindowSetter.newMap;
import static attack_system.unlockLevel.unlockDungeons;
import static attack_system.unlockLevel.unlocking;
import desert.desert;


import potwor.Potwor;


/**
 *
 * @author allan
 */
public class desertCity extends javax.swing.JFrame {

    /** Creates new form lochy */
    public desertCity() {
        initComponents();
       
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyguardAttack = new javax.swing.JButton();
        bossAnubisAttack = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        cityBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyguardAttack.setBackground(new java.awt.Color(182, 153, 111));
        bodyguardAttack.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        bodyguardAttack.setText("Strażnicy");
        bodyguardAttack.setBorder(null);
        bodyguardAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyguardAttackActionPerformed(evt);
            }
        });
        getContentPane().add(bodyguardAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 90, -1));

        bossAnubisAttack.setBackground(new java.awt.Color(182, 153, 111));
        bossAnubisAttack.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        bossAnubisAttack.setText("Boss");
        bossAnubisAttack.setBorder(null);
        bossAnubisAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bossAnubisAttackActionPerformed(evt);
            }
        });
        getContentPane().add(bossAnubisAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 90, -1));

        Back.setBackground(new java.awt.Color(182, 153, 111));
        Back.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        Back.setText("Wróć");
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 90, -1));

        cityBackground.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/monstersMiasto.jpg")); // NOI18N
        getContentPane().add(cityBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bodyguardAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyguardAttackActionPerformed
      if(unlockDungeons>1  ){   new bodyguardAttack().setVisible(true);}
    }//GEN-LAST:event_bodyguardAttackActionPerformed

    private void bossAnubisAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bossAnubisAttackActionPerformed
     if(unlockDungeons>2 ){    new bossAnubisAttack().setVisible(true);}
    }//GEN-LAST:event_bossAnubisAttackActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
          new desert().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desertCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desertCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desertCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desertCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desertCity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton bodyguardAttack;
    private javax.swing.JButton bossAnubisAttack;
    private javax.swing.JLabel cityBackground;
    // End of variables declaration//GEN-END:variables

}
