/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealers;


import Equipment.swordAzeroth;
import Equipment.swordOutland;
import dealersSQL.ArmorSQLSelectValue;
import static dealersSQL.ArmorSQLSelectValue.selectPrizeSword;
import static dealersSQL.SqlPrizeDealers.selectIdSword;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import main.mainMain;


/**
 *
 * @author allan
 */
public class dealersMainMain extends javax.swing.JFrame {

    /**
     * Creates new form monsters
     */
  
    public dealersMainMain() {
        initComponents();
         try {
            selectIdSword(swordAzeroth.nameItem);              
           // selectPrizeSword(idSwordHandler);          
            selectIdSword(swordOutland.nameItem);
            
            //selectPrizeSword(swordOutland.idSw);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(dealerArmor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        armorWeapon = new javax.swing.JPanel();
        openDealerArmorWeapon = new javax.swing.JButton();
        armorWeaponDealer = new javax.swing.JLabel();
        enchants = new javax.swing.JPanel();
        enchantsPhoto = new javax.swing.JLabel();
        enchantsButton = new javax.swing.JButton();
        jeweler = new javax.swing.JPanel();
        jewelerPhoto = new javax.swing.JLabel();
        jewelerButton = new javax.swing.JButton();
        word = new javax.swing.JLabel();
        backToMainMain = new javax.swing.JButton();
        potionDealers = new javax.swing.JPanel();
        openDealersPotion = new javax.swing.JButton();
        potionDealersphoto = new javax.swing.JLabel();
        openMarket = new javax.swing.JLabel();
        jeweler1 = new javax.swing.JPanel();
        jewelerPhoto1 = new javax.swing.JLabel();
        jewelerButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 484));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 484));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        armorWeapon.setBackground(new java.awt.Color(5, 27, 53));
        armorWeapon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        openDealerArmorWeapon.setBackground(new java.awt.Color(255, 255, 255));
        openDealerArmorWeapon.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        openDealerArmorWeapon.setText("Rynsztunek");
        openDealerArmorWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openDealerArmorWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDealerArmorWeaponActionPerformed(evt);
            }
        });

        armorWeaponDealer.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/rynsztunek.jpg")); // NOI18N

        javax.swing.GroupLayout armorWeaponLayout = new javax.swing.GroupLayout(armorWeapon);
        armorWeapon.setLayout(armorWeaponLayout);
        armorWeaponLayout.setHorizontalGroup(
            armorWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armorWeaponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(armorWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(openDealerArmorWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(armorWeaponDealer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        armorWeaponLayout.setVerticalGroup(
            armorWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armorWeaponLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(armorWeaponDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openDealerArmorWeapon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(armorWeapon, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 136, -1, -1));

        enchants.setBackground(new java.awt.Color(5, 27, 53));
        enchants.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        enchantsPhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/gemsDealer2.jpg")); // NOI18N

        enchantsButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        enchantsButton.setText("Enchant");
        enchantsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enchantsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enchantsLayout = new javax.swing.GroupLayout(enchants);
        enchants.setLayout(enchantsLayout);
        enchantsLayout.setHorizontalGroup(
            enchantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enchantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enchantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(enchantsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enchantsPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enchantsLayout.setVerticalGroup(
            enchantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enchantsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enchantsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enchantsButton)
                .addContainerGap())
        );

        getContentPane().add(enchants, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 136, -1, -1));

        jeweler.setBackground(new java.awt.Color(5, 27, 53));
        jeweler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jewelerPhoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/jewelry.jpg")); // NOI18N

        jewelerButton.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jewelerButton.setText("Biżuteria");

        javax.swing.GroupLayout jewelerLayout = new javax.swing.GroupLayout(jeweler);
        jeweler.setLayout(jewelerLayout);
        jewelerLayout.setHorizontalGroup(
            jewelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jewelerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jewelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jewelerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jewelerPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jewelerLayout.setVerticalGroup(
            jewelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jewelerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jewelerPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jewelerButton)
                .addContainerGap())
        );

        getContentPane().add(jeweler, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 136, -1, -1));

        word.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setText("Bazar");
        getContentPane().add(word, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 200, -1));

        backToMainMain.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        backToMainMain.setText("Wróć");
        backToMainMain.setBorder(null);
        backToMainMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMainActionPerformed(evt);
            }
        });
        getContentPane().add(backToMainMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 409, 110, 30));

        potionDealers.setBackground(new java.awt.Color(5, 27, 53));
        potionDealers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        openDealersPotion.setBackground(new java.awt.Color(255, 255, 255));
        openDealersPotion.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        openDealersPotion.setText("Alchemia");
        openDealersPotion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openDealersPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDealersPotionActionPerformed(evt);
            }
        });

        potionDealersphoto.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/potionDealer2.jpg")); // NOI18N

        javax.swing.GroupLayout potionDealersLayout = new javax.swing.GroupLayout(potionDealers);
        potionDealers.setLayout(potionDealersLayout);
        potionDealersLayout.setHorizontalGroup(
            potionDealersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potionDealersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(potionDealersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(openDealersPotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(potionDealersphoto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        potionDealersLayout.setVerticalGroup(
            potionDealersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potionDealersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potionDealersphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openDealersPotion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(potionDealers, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 136, -1, -1));

        openMarket.setBackground(new java.awt.Color(51, 51, 51));
        openMarket.setForeground(new java.awt.Color(255, 255, 255));
        openMarket.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/tloDlaHandlarzy.jpg")); // NOI18N
        getContentPane().add(openMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 510));

        jeweler1.setBackground(new java.awt.Color(5, 27, 53));
        jeweler1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jewelerPhoto1.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/jewelry.jpg")); // NOI18N

        jewelerButton1.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jewelerButton1.setText("Biżuteria");

        javax.swing.GroupLayout jeweler1Layout = new javax.swing.GroupLayout(jeweler1);
        jeweler1.setLayout(jeweler1Layout);
        jeweler1Layout.setHorizontalGroup(
            jeweler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jeweler1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jeweler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jewelerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jewelerPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jeweler1Layout.setVerticalGroup(
            jeweler1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jeweler1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jewelerPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jewelerButton1)
                .addContainerGap())
        );

        getContentPane().add(jeweler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 136, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openDealerArmorWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDealerArmorWeaponActionPerformed
        new dealerArmor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_openDealerArmorWeaponActionPerformed

    private void enchantsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enchantsButtonActionPerformed

        
    }//GEN-LAST:event_enchantsButtonActionPerformed

    private void backToMainMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMainActionPerformed
      new mainMain().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_backToMainMainActionPerformed

    private void openDealersPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDealersPotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openDealersPotionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealersMainMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealersMainMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealersMainMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealersMainMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dealersMainMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel armorWeapon;
    private javax.swing.JLabel armorWeaponDealer;
    private javax.swing.JButton backToMainMain;
    private javax.swing.JPanel enchants;
    private javax.swing.JButton enchantsButton;
    private javax.swing.JLabel enchantsPhoto;
    private javax.swing.JPanel jeweler;
    private javax.swing.JPanel jeweler1;
    private javax.swing.JButton jewelerButton;
    private javax.swing.JButton jewelerButton1;
    private javax.swing.JLabel jewelerPhoto;
    private javax.swing.JLabel jewelerPhoto1;
    private javax.swing.JButton openDealerArmorWeapon;
    private javax.swing.JButton openDealersPotion;
    private javax.swing.JLabel openMarket;
    private javax.swing.JPanel potionDealers;
    private javax.swing.JLabel potionDealersphoto;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables
}
