/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desert;


import static attack_system.unlockLevel.unlocking;
import static creatingChar.creatingCharacter.object_character;
import static desert.desert.sphinxDesert;



/**
 *
 * @author allan
 */
public class sphinxAttack extends javax.swing.JFrame {

      
  int valueGlad=object_character.zycie;
  int valueSphinx=sphinxDesert.potworZycie;
  
    String champInt=String.valueOf(object_character.zycie);
    String sphinxInt=String.valueOf(sphinxDesert.potworZycie);
  
    public sphinxAttack() {
        initComponents();
            
   champBar.setString(champInt);
   sphinxBa.setString(sphinxInt);
    champBar.setValue(object_character.zycie);
    sphinxBa.setValue(sphinxDesert.potworZycie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sphinxPanel = new javax.swing.JPanel();
        sphinxLab = new javax.swing.JLabel();
        sphinxBa = new javax.swing.JProgressBar();
        sphinxR = new javax.swing.JTextField();
        champPanel = new javax.swing.JPanel();
        champLabel = new javax.swing.JLabel();
        champBar = new javax.swing.JProgressBar();
        champ = new javax.swing.JTextField();
        attackBut = new javax.swing.JButton();
        backgroundSphinx = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sphinxPanel.setBackground(new java.awt.Color(182, 153, 111));
        sphinxPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        sphinxPanel.setForeground(new java.awt.Color(182, 153, 111));

        sphinxLab.setForeground(new java.awt.Color(91, 109, 94));
        sphinxLab.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/sphinx2.jpg")); // NOI18N
        sphinxLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sphinxLab.setDoubleBuffered(true);

        sphinxBa.setStringPainted(true);

        sphinxR.setEditable(false);
        sphinxR.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        sphinxR.setForeground(new java.awt.Color(91, 109, 94));
        sphinxR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sphinxR.setText("Sphinx");
        sphinxR.setCaretColor(new java.awt.Color(91, 109, 94));
        sphinxR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphinxRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sphinxPanelLayout = new javax.swing.GroupLayout(sphinxPanel);
        sphinxPanel.setLayout(sphinxPanelLayout);
        sphinxPanelLayout.setHorizontalGroup(
            sphinxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sphinxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sphinxLab, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sphinxR)
            .addComponent(sphinxBa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sphinxPanelLayout.setVerticalGroup(
            sphinxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sphinxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sphinxLab, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sphinxR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sphinxBa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(sphinxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 320));

        champPanel.setBackground(new java.awt.Color(182, 153, 111));
        champPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, null));
        champPanel.setForeground(new java.awt.Color(182, 153, 111));

        champLabel.setForeground(new java.awt.Color(91, 109, 94));
        champLabel.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/champ.jpg")); // NOI18N
        champLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        champLabel.setDoubleBuffered(true);

        champBar.setStringPainted(true);

        champ.setEditable(false);
        champ.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        champ.setForeground(new java.awt.Color(91, 109, 94));
        champ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        champ.setText("Gladiator");
        champ.setCaretColor(new java.awt.Color(91, 109, 94));

        javax.swing.GroupLayout champPanelLayout = new javax.swing.GroupLayout(champPanel);
        champPanel.setLayout(champPanelLayout);
        champPanelLayout.setHorizontalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(champ)
            .addComponent(champBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        champPanelLayout.setVerticalGroup(
            champPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(champLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(champPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 82, -1, 320));

        attackBut.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        attackBut.setText("Atakuj");
        attackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButActionPerformed(evt);
            }
        });
        getContentPane().add(attackBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        backgroundSphinx.setIcon(new javax.swing.ImageIcon("/Users/allan/Desktop/gallery_photos_game/pustynia_tlo.jpeg")); // NOI18N
        getContentPane().add(backgroundSphinx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButActionPerformed
             if(sphinxDesert.potworZycie > 0 && object_character.zycie > 0){
            if(sphinxDesert.potworZycie == 0 || object_character.zycie==0){
                System.out.println("MARTWI");
            }
            else{
                 object_character.atak(sphinxDesert);
                 sphinxDesert.atakPotwor(object_character);            
                 valueGlad=object_character.zycie;
                 valueSphinx=sphinxDesert.potworZycie;
                 champInt=String.valueOf(object_character.zycie); 
                 sphinxInt=String.valueOf(sphinxDesert.potworZycie);
     
     
                        champBar.setValue(valueGlad);
                        sphinxBa.setValue(valueSphinx);
                        champBar.setString(champInt);
                        sphinxBa.setString(sphinxInt);
                }
              if(sphinxDesert.potworZycie==0){unlocking(1);}
         if(object_character.zycie<=0){ sphinxDesert.potworZycie=sphinxDesert.potworZycieWartownik;}
        }
                                            

    }//GEN-LAST:event_attackButActionPerformed

    private void sphinxRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphinxRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sphinxRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sphinxAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sphinxAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sphinxAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sphinxAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sphinxAttack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackBut;
    private javax.swing.JLabel backgroundSphinx;
    private javax.swing.JTextField champ;
    private javax.swing.JProgressBar champBar;
    private javax.swing.JLabel champLabel;
    private javax.swing.JPanel champPanel;
    private javax.swing.JProgressBar sphinxBa;
    private javax.swing.JLabel sphinxLab;
    private javax.swing.JPanel sphinxPanel;
    private javax.swing.JTextField sphinxR;
    // End of variables declaration//GEN-END:variables
}
